###

POST http://localhost:4000/v1/admin/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjZXZhLmNvbSIsInN1YiI6IjMiLCJhdWQiOlsiY2V2YS5jb20iXSwiZXhwIjoxNjUwMzgyMTQ5LjYzMDIzMjYsIm5iZiI6MTY1MDI5NTc0OS42MzAyMzIzLCJpYXQiOjE2NTAyOTU3NDkuNjMwMjMxOX0.L8VHbMLTS-vrUpjH2ZP8MjsbuD0qPGcHcwJQ6VnnSf0

{
  "id": "105",
  "title": "added smth new",
  "winner": "A2",
  "description": "ha ha haaa"
}

###

GET http://localhost:4000/v1/admin/delete/122
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjZXZhLmNvbSIsInN1YiI6IjUiLCJhdWQiOlsiY2V2YS5jb20iXSwiZXhwIjoxNjUwMjA3MDYyLjUwNzgyNiwibmJmIjoxNjUwMTIwNjYyLjUwNzgyNiwiaWF0IjoxNjUwMTIwNjYyLjUwNzgyNTZ9.1mSOoPXVxjGQ6va_FJdxsglIZ83XfIpPYy_UCV3xVg8
