GET http://localhost:4000/v1/all


###

POST http://localhost:4000/v1/signin
Content-Type: application/json

{
    "email": "mishutrz2@yahoo.com",
    "password": "arlemanosel"
}

###

GET http://localhost:4000/v1/my
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjZXZhLmNvbSIsInN1YiI6IjMzIiwiYXVkIjpbImNldmEuY29tIl0sImV4cCI6MTY1MDQwNzQ4MC4wODU2NTc0LCJuYmYiOjE2NTAzMjEwODAuMDg1NjU3MSwiaWF0IjoxNjUwMzIxMDgwLjA4NTY1NjZ9.wKPmKCVwhVKdspS6X1m68NJc7SqHNuFjGUUlV72AW2w


###

GET http://localhost:4000/v1/user-info
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjZXZhLmNvbSIsInN1YiI6IjMzIiwiYXVkIjpbImNldmEuY29tIl0sImV4cCI6MTY1MDQwNzQ4MC4wODU2NTc0LCJuYmYiOjE2NTAzMjEwODAuMDg1NjU3MSwiaWF0IjoxNjUwMzIxMDgwLjA4NTY1NjZ9.wKPmKCVwhVKdspS6X1m68NJc7SqHNuFjGUUlV72AW2w
